# Generated by Django 3.2.8 on 2022-02-21 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='post_code_city',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
