# Generated by Django 3.2.8 on 2022-03-21 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_profile_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='company_adress',
            field=models.CharField(blank=True, max_length=60, verbose_name='Company adress'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='company_name',
            field=models.CharField(blank=True, max_length=40, verbose_name='Company name'),
        ),
    ]
