# Generated by Django 3.2.8 on 2022-01-27 11:43

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import shortuuid.django_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=None, validators=[django.core.validators.MinValueValidator(1950, 'Enter a valid year.'), django.core.validators.MaxValueValidator(2050, 'Enter a valid year.')])),
                ('fuel_type', models.CharField(choices=[('', '---------'), ('Gasoline', 'Gasoline'), ('Diesel', 'Diesel'), ('Electric', 'Electric'), ('Hybrid', 'Hybrid'), ('PB+LPG', 'PB+LPG')], default=None, max_length=15)),
                ('engine', models.CharField(blank=True, max_length=15, null=True)),
                ('vin', models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.MinLengthValidator(17, 'This VIN number is too short.')])),
                ('extra_info', models.TextField(blank=True, max_length=300, null=True, verbose_name='Remarks')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('uuid', shortuuid.django_fields.ShortUUIDField(alphabet=None, editable=False, length=12, max_length=20, prefix='', unique=True)),
            ],
            options={
                'ordering': ('-date_updated',),
            },
        ),
        migrations.CreateModel(
            name='CarMake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_make', models.CharField(max_length=30, verbose_name='Make')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(blank=True, default=None, max_length=150, verbose_name='Service')),
                ('service_price', models.DecimalField(decimal_places=2, default=None, max_digits=20)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='san_diego.car')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-date_added',),
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=40, verbose_name='Name')),
                ('phone_number', models.CharField(blank=True, max_length=9, null=True)),
                ('uuid', shortuuid.django_fields.ShortUUIDField(alphabet=None, editable=False, length=12, max_length=20, prefix='', unique=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='CarParts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_part', models.CharField(blank=True, max_length=30, null=True, verbose_name='Part')),
                ('part_price', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=20)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='san_diego.service')),
            ],
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make_name', models.CharField(max_length=30)),
                ('model_name', models.CharField(max_length=30, verbose_name='Model')),
                ('make', models.ForeignKey(max_length=30, on_delete=django.db.models.deletion.CASCADE, to='san_diego.carmake', verbose_name='Make')),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='car_make',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='san_diego.carmake'),
        ),
        migrations.AddField(
            model_name='car',
            name='car_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='san_diego.carmodel'),
        ),
        migrations.AddField(
            model_name='car',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='san_diego.client'),
        ),
        migrations.AddField(
            model_name='car',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
