# Generated by Django 3.2.8 on 2022-02-01 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('san_diego', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carparts',
            name='part_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_name',
            field=models.CharField(default=None, max_length=150, verbose_name='Service'),
        ),
    ]
