# Generated by Django 3.2.8 on 2022-02-06 12:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('san_diego', '0002_auto_20220201_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='fuel_type',
            field=models.CharField(blank=True, choices=[('', '---------'), ('Gasoline', 'Gasoline'), ('Diesel', 'Diesel'), ('Electric', 'Electric'), ('Hybrid', 'Hybrid'), ('PB+LPG', 'PB+LPG')], default=None, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='year',
            field=models.IntegerField(blank=True, default=None, null=True, validators=[django.core.validators.MinValueValidator(1950, 'Enter a valid year.'), django.core.validators.MaxValueValidator(2050, 'Enter a valid year.')]),
        ),
    ]
