# Generated by Django 3.2.8 on 2022-02-11 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('san_diego', '0003_auto_20220206_1317'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={},
        ),
        migrations.AlterField(
            model_name='service',
            name='date_added',
            field=models.DateField(auto_now_add=True),
        ),
    ]
