# Generated by Django 3.2.8 on 2022-02-11 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('san_diego', '0005_alter_service_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='date_added',
            field=models.DateField(auto_now_add=True),
        ),
    ]
