# Generated by Django 3.2.8 on 2022-02-13 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('san_diego', '0007_auto_20220213_1027'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarParts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_part', models.CharField(blank=True, max_length=30, null=True, verbose_name='Part')),
                ('part_price', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='san_diego.service')),
            ],
        ),
        migrations.DeleteModel(
            name='CarPart',
        ),
    ]
