# Generated by Django 3.2.8 on 2022-02-13 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('san_diego', '0010_rename_date_added_carpart_pdate_added'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carpart',
            old_name='pdate_added',
            new_name='date_added',
        ),
    ]
