# Generated by Django 3.2.8 on 2022-02-16 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('san_diego', '0012_rename_date_added_carpart_pdate_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='service_name',
            field=models.CharField(blank=True, default=None, max_length=150, null=True, verbose_name='Service'),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=20, null=True),
        ),
    ]
