# Generated by Django 3.2.8 on 2022-02-16 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('san_diego', '0013_auto_20220216_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='service_name',
            field=models.CharField(default=None, max_length=150, verbose_name='Service'),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_price',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=20),
        ),
    ]
