# Generated by Django 3.2.8 on 2022-02-18 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('san_diego', '0014_auto_20220216_0939'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carpart',
            old_name='pdate_added',
            new_name='date_added',
        ),
    ]
