# Generated by Django 3.2.8 on 2022-02-18 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('san_diego', '0015_rename_pdate_added_carpart_date_added'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carpart',
            old_name='date_added',
            new_name='pdate_added',
        ),
    ]
