# Generated by Django 3.2.8 on 2022-02-25 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('san_diego', '0016_rename_date_added_carpart_pdate_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carpart',
            name='pdate_added',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='date_added',
            field=models.DateField(auto_now=True),
        ),
    ]
