# Generated by Django 3.2.8 on 2022-02-25 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('san_diego', '0022_auto_20220225_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carpart',
            name='pdate_added',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='service',
            name='date_added',
            field=models.DateField(),
        ),
    ]
