# Generated by Django 3.2.8 on 2022-02-25 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('san_diego', '0023_auto_20220225_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carpart',
            name='pdate_added',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='date_added',
            field=models.DateField(auto_now_add=True),
        ),
    ]
