# Generated by Django 3.2.8 on 2022-02-27 12:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('san_diego', '0030_alter_car_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carpart',
            name='pdate_added',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
