# Generated by Django 3.2.8 on 2022-02-27 12:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('san_diego', '0031_alter_carpart_pdate_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='date_added',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
