# Generated by Django 3.2.8 on 2022-03-03 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('san_diego', '0032_alter_service_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carpart',
            name='car_part',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Part'),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_name',
            field=models.CharField(default=None, max_length=100, verbose_name='Service'),
        ),
    ]
