# Generated by Django 3.2.8 on 2022-03-21 17:12

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('san_diego', '0033_auto_20220303_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_make',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='san_diego.carmake', verbose_name='Car make'),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='san_diego.carmodel', verbose_name='Car model'),
        ),
        migrations.AlterField(
            model_name='car',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='san_diego.client', verbose_name='Client'),
        ),
        migrations.AlterField(
            model_name='car',
            name='engine',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Engine'),
        ),
        migrations.AlterField(
            model_name='car',
            name='fuel_type',
            field=models.CharField(blank=True, choices=[('', '---------'), ('Gasoline', 'Gasoline'), ('Diesel', 'Diesel'), ('Electric', 'Electric'), ('Hybrid', 'Hybrid'), ('PB+LPG', 'PB+LPG')], default=None, max_length=15, null=True, verbose_name='Fuel type'),
        ),
        migrations.AlterField(
            model_name='car',
            name='year',
            field=models.IntegerField(blank=True, default=None, null=True, validators=[django.core.validators.MinValueValidator(1950, 'Enter a valid year.'), django.core.validators.MaxValueValidator(2050, 'Enter a valid year.')], verbose_name='Year'),
        ),
        migrations.AlterField(
            model_name='carpart',
            name='part_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Part price'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone_number',
            field=models.CharField(blank=True, max_length=9, null=True, verbose_name='Phone number'),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_price',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=20, verbose_name='Service price'),
        ),
    ]
